apiVersion: apps/v1
kind: Deployment
metadata:
  name: about
spec:
  replicas: 1
  selector:
    matchLabels:
      app: about
  template:
    metadata:
      labels:
        app: about
    spec:
      containers:
      - image: okteto.dev/about:latest
        name: about
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/S-html.zip"
        - name: Vless_UUID
          value: "34a8e075-9b5b-42b1-a360-3e57a41c8970"
        - name: Vless_Path
          value: "/tonyjeans"
        - name: Vmess_UUID
          value: "34a8e075-9b5b-42b1-a360-3e57a41c8970"
        - name: Vmess_Path
          value: "/jackjones"
        - name: Share_Path
          value: "/v2link"
